ncc-erp/ncc-erp-ams-fe

src/api/baseApi.ts
src/components/elements/TotalDetail.tsx
src/interfaces/index.d.ts
src/pages/accessory/list.tsx
src/pages/consumables/list.tsx
src/pages/hardware/list-assign.tsx
src/pages/hardware/list-broken.tsx
src/pages/hardware/list-expiration.tsx
src/pages/hardware/list-pending.tsx
src/pages/hardware/list-readyToDeploy.tsx
src/pages/hardware/list-watiting-confirm.tsx
src/pages/hardware/list.tsx
src/pages/report/list.tsx
src/pages/tax_token/list-waiting.tsx
src/pages/tax_token/list.tsx
src/pages/tools/list-waiting.tsx
src/pages/tools/list.tsx
src/styles/antd.less

Task 50851: https://ops.nccsoft.vn/DefaultCollection/NCC-ITTools/_workitems/edit/50851
Evidence: https://www.loom.com/share/f5f3da26cc804cc584d74a71a0a28615

#50851: Add total detail 

---

src/components/dashboard/locations/assets-summary-table/index.tsx
src/pages/location/detailAccessory.tsx
src/pages/location/detailConsumable.tsx
src/pages/location/details.tsx

- Thêm hiển thị số luọng vào trang location_detail
- Sửa đường dẫn url của Token thuế với Tool ở trang Dashboard
Evidence: https://www.loom.com/share/a82c4253718141579122617dac0bf9c0

Update total detail for location detail & fix url at dashboard

---

README.MD

- Task #51101: https://ops.nccsoft.vn/DefaultCollection/NCC-ITTools/_workitems/edit/51101
- Evidence: https://www.loom.com/share/46ceaee2b7d54901865bef889bdf9b95

#51101: Update Readme 

---

src/components/elements/TotalDetail.tsx
src/pages/accessory/list.tsx
src/pages/consumables/list.tsx
src/pages/hardware/list-assign.tsx
src/pages/hardware/list-broken.tsx
src/pages/hardware/list-expiration.tsx
src/pages/hardware/list-pending.tsx
src/pages/hardware/list-readyToDeploy.tsx
src/pages/hardware/list-watiting-confirm.tsx
src/pages/hardware/list.tsx
src/pages/location/detailAccessory.tsx
src/pages/location/detailConsumable.tsx
src/pages/location/details.tsx
src/pages/tax_token/list-waiting.tsx
src/pages/tax_token/list.tsx
src/pages/tools/list-waiting.tsx
src/pages/tools/list.tsx

- Task: https://ops.nccsoft.vn/DefaultCollection/NCC-ITTools/_workitems/edit/51172
- Evidence: https://www.loom.com/share/2b79bb6c7a714b4586a6b261b4a6214f

#51172: Fix bug total detail not reload

---

public/locales/vi/common.json
src/pages/categories/list.tsx

- Task : https://ops.nccsoft.vn/DefaultCollection/NCC-ITTools/_workitems/edit/51595
- Evidence:: https://www.loom.com/share/7ddcc02d73764a538abaf96c54c55e3a

#51595: Fix Tool display 

---

src/App.tsx
src/components/dashboard/locations/assets-summary-table/index-all-location.tsx
src/components/dashboard/locations/assets-summary-table/index.tsx
src/components/layout/header/index.tsx
src/components/layout/sider/styles.ts
src/pages/hardware_client/list-assign.tsx
src/pages/hardware_client/list-watiting-confirm.tsx

Fix button Display

---

src/components/dashboard/locations/assets-summary-table/index.tsx
src/components/layout/sider/index.tsx
src/pages/hardware_client/list-watiting-confirm.tsx

Fix permission in side bar

---

src/components/Modal/MModal/index.tsx
src/hooks/useResponsiveModalWidth.ts
src/pages/hardware/create.tsx
src/styles/antd.less
src/styles/hardware.less
src/styles/qr-code.less

https://github.com/orgs/ncc-erp/projects/5/views/1?pane=issue&itemId=77444839
https://github.com/orgs/ncc-erp/projects/5/views/1?pane=issue&itemId=77461090

reponsive modal and mobile view

---

public/locales/vi/common.json
src/pages/hardware/muti-qr-cards.tsx
src/pages/hardware/qr-control-panel.tsx
src/pages/hardware/scanner.tsx
src/pages/hardware/single-qr-card.tsx
src/styles/qr-code.less
src/styles/single-qr-code.less

- Related Issue #36 
- Related Issue #37

Fix show modal when scan invalid qr

---

public/locales/vi/common.json
src/components/layout/header/index.tsx
src/pages/hardware/qr-code.tsx
src/pages/hardware_client/list.tsx
src/styles/qr-code.less

- Add qr code page Thiet Bi Khach Hang + add qr code button on header
- Optimization
- #50

Fix ui and add qr code to page Thiet Bi Khach Hang

---

public/locales/vi/common.json
src/AccessControl.ts
src/App.tsx
src/components/layout/sider/index.tsx
src/constants/assets.ts
src/interfaces/hardware.d.ts
src/pages/hardware/create.tsx
src/pages/hardware/edit.tsx
src/pages/hardware/index.ts
src/pages/hardware/list-maintenance.tsx
src/pages/hardware/modal.tsx
src/pages/hardware/search-filter-form.tsx
src/pages/hardware/show.tsx
src/pages/hardware/table-column.tsx
src/pages/hardware/table.tsx
src/pages/hardware/tool-bar.tsx
src/ultils/ConvertHardwareData.ts

- Add Add Maintenance Time for assets, show maintenance list
- #68 
- https://www.awesomescreenshot.com/video/40105340?key=928614380f7e67f9958744e2133c62b2

Add Maintenance Time for assets, show maintenance list

---

public/locales/vi/common.json
src/interfaces/consumables.d.ts
src/pages/consumables/create.tsx
src/pages/consumables/edit.tsx
src/pages/consumables/list.tsx
src/pages/consumables/show.tsx
src/pages/consumables/table-column.tsx

- Add Add Maintenance for consumables
- #73 
- https://www.awesomescreenshot.com/video/40675904?key=1f357c703ed35ccf6243aaca4f5a6c7b

Add maintenance time for consumables

---

src/pages/hardware/create.tsx
src/pages/hardware_client/create.tsx
src/pages/manager_users/list.tsx

- Add Mezon Id column and Add search for project and customer
- #45  
- #71 
- https://www.awesomescreenshot.com/video/40752057?key=b913cbae62b21eeac639f432d9c1b444

Add Mezon Id column and Add search for project and customer

---

public/locales/vi/common.json
src/AccessControl.ts
src/App.tsx
src/api/baseApi.ts
src/components/layout/sider/index.tsx
src/constants/webhook.ts
src/interfaces/consumables.d.ts
src/interfaces/hardware.d.ts
src/interfaces/webhook.d.ts
src/pages/consumables/create.tsx
src/pages/consumables/edit.tsx
src/pages/consumables/list-maintenance.tsx
src/pages/consumables/list.tsx
src/pages/consumables/table-column.tsx
src/pages/hardware/create.tsx
src/pages/hardware/edit.tsx
src/pages/hardware/list.tsx
src/pages/hardware/table-column.tsx
src/pages/webhook/create.tsx
src/pages/webhook/detail.tsx
src/pages/webhook/edit.tsx
src/pages/webhook/list.tsx
src/pages/webhook/show.tsx
src/styles/detailWebhook.less

- Add Mezon webhook support for admin
- https://github.com/ncc-erp/ncc-erp-workflow-w2-ui/issues/360
- https://www.awesomescreenshot.com/video/40923699?key=5a1b568a3b8db863b7698e6bb7506744
- https://www.awesomescreenshot.com/video/41093789?key=99566b39eb1c833aea3235badfed8a51
- https://www.awesomescreenshot.com/video/41167617?key=f06c2b906928c97d208d8e09173fd231

Add Mezon webhook support for admin

---

public/locales/vi/common.json
src/AccessControl.ts
src/App.tsx
src/api/baseApi.ts
src/components/layout/sider/index.tsx
src/interfaces/hardware.d.ts
src/pages/hardware/create.tsx
src/pages/hardware/edit.tsx
src/pages/hardware/index.ts
src/pages/hardware/list-rental-customers.tsx
src/pages/hardware/table-column-rental-customers.tsx
src/pages/hardware/table.tsx

- add rental-customer for assets
- #112 
https://www.awesomescreenshot.com/video/42497534?key=9acbc53d9ed07255c530b2421c5b785f

feat(AMS-112): add rental-customer for assets

---

src/hooks/useAppSearchParams/config.ts
src/hooks/useAppSearchParams/index.ts
src/hooks/useAppSearchParams/types.ts
src/pages/accessory/list.tsx
src/pages/consumables/list-maintenance.tsx
src/pages/consumables/list.tsx
src/pages/dashboard/index.tsx
src/pages/dashboard/list_checkin_checkout.tsx
src/pages/hardware/list-assign.tsx
src/pages/hardware/list-broken.tsx
src/pages/hardware/list-expiration.tsx
src/pages/hardware/list-maintenance.tsx
src/pages/hardware/list-pending.tsx
src/pages/hardware/list-readyToDeploy.tsx
src/pages/hardware/list-watiting-confirm.tsx
src/pages/hardware/list.tsx
src/pages/hardware_client/list-assign.tsx
src/pages/hardware_client/list-broken.tsx
src/pages/hardware_client/list-expiration.tsx
src/pages/hardware_client/list-pending.tsx
src/pages/hardware_client/list-readyToDeploy.tsx
src/pages/hardware_client/list-watiting-confirm.tsx
src/pages/hardware_client/list.tsx
src/pages/report/list.tsx
src/pages/tax_token/list-waiting.tsx
src/pages/tax_token/list.tsx
src/pages/tools/list-waiting.tsx
src/pages/tools/list.tsx
src/pages/users/list-tax-tokens.tsx
src/pages/users/list.tsx

- Apply filter params config for all pages
- Related Issue[ #99 ](https://github.com/ncc-erp/ncc-erp-ams-fe/issues/99)
https://github.com/user-attachments/assets/b5ee18a1-26ea-40c1-ac69-ee9cf0bb223e

refactor: Apply filter params config for all pages

---

public/locales/vi/common.json
src/AccessControl.ts
src/App.tsx
src/api/baseApi.ts
src/components/layout/sider/index.tsx
src/interfaces/webhook_logs.d.ts
src/pages/audit/webhook_logs/list.tsx
src/pages/audit/webhook_logs/show.tsx

- Komu Logs UI for Admin
- #100
- https://www.awesomescreenshot.com/video/41510396?key=65207c50af363df71e0aa2b1f24aa431

Webhook Logs UI for Admin

---

SETUP.md
code-guidelines.md

- create SETUP.md and code-guidelines.md
- #130

feat(AMS-130): create SETUP.md and code-guidelines.md

---

jest.config.ts
src/__tests__/components/layout/header/Header.test.tsx
src/components/layout/header/index.tsx

- Unit test for header component
- ### Related Issues
- #159

feat(AMS-159): add uni test for header component

---

jest.config.ts
src/__tests__/components/elements/uploadImage/UploadImage.test.tsx
src/setupTests.ts
tsconfig.json

- Unit test for Upload Image component
- ### Related Issues
- #158

Feat/158: Unit test for Upload Image component

---

src/styles/antd.less

- Update hover behavior for item in submenu when sidebar collapsed
- Related Issue #168

feat(AMS-168): update hover behavior for item in submenu when sidebar collapsed

---

jest.config.ts
src/__tests__/pages/login/LoginPage.test.tsx

- Check page render
- Check login flow
- ### Related Issues
- #161

Feat/161: [Component testing] Login page
